version: "3"

services:
    # image project
    app:
        build:
            context: ./docker/
            dockerfile: Dockerfile
        ports:
            - '8080:80'
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
        depends_on:
            - redis
        networks:
            - trawler

    # db mysql
    mysql:
        image: mysql:5.7
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        volumes:
            - ./.docker/mysql/dbdata:/var/lib/mysql
        ports:
            - "3388:3306"
        networks:
            - trawler

    # redis
    redis:
        image: redis:alpine
        networks:
            - trawler

networks:
    trawler:
        driver: bridge