version: "3"

services:
    # image project
    app:
        build:
            context: ./docker/
            dockerfile: Dockerfile
        restart: unless-stopped
        ports:
            - '${APP_PORT:-80}:80'
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
        depends_on:
            - redis
        networks:
            - trawler

    # db mysql
    mysql:
        image: mysql/mysql-server:5.7
        command: --ignore-db-dir=lost+found --innodb_use_native_aio=0 --explicit_defaults_for_timestamp
        restart: unless-stopped
        environment:
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        volumes:
            - trawler-mysql:/var/lib/mysql
            # - /.docker/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        ports:
            - "${DB_PORT:-3306}:3306"
        networks:
            - trawler

    # redis
    redis:
        image: redis:alpine
        ports:
        - '${REDIS_PORT:-6379}:6379'
        volumes:
            - trawler-redis:/data
        networks:
            - trawler

networks:
    trawler:
        driver: bridge

volumes:
    trawler-mysql:
        driver: local
    trawler-redis:
        driver: local